# Site settings
title: Danny Caballero
email: caballero@pa.msu.edu
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts and posts from MSU physics professor Danny Caballero.
  Posted work is licensed under a Creative Commons BY-NC-SA 4.0 License unless noted otherwise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dannycab.github.io" # the base hostname & protocol for your site
twitter_username: physicistdanny
github_username:  dannycab

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from
